from src.remote_service_algorithms.shared.enums import get_prop

OUTDATED_RENAMES = {
    "heating.power.cumulativeProduced/value": get_prop(
        "HEATING_POWER_PRODUCTION_CUMULATIVE_VALUE"
    ).value,
    "heating.power.cumulativePurchased/value": get_prop(
        "HEATING_POWER_PURCHASE_CUMULATIVE_VALUE"
    ).value,
    "heating.power.cumulativeSold/value": get_prop(
        "HEATING_POWER_SOLD_CUMULATIVE_VALUE"
    ).value,
    "heating.sensors.power.output/value": get_prop(
        "HEATING_POWER_PRODUCTION_CURRENT_VALUE"
    ).value,
    "heating.sensors.volumetricFlow.return/value": get_prop(
        "HEATING_SENSORS_VOLUMETRICFLOW_RETURN_VALUE"
    ).value,
    "heating.burner.modulation/value": get_prop(
        "HEATING_BURNERS_0_MODULATION_VALUE"
    ).value,
    "heating.burner.statistics/starts": get_prop(
        "HEATING_BURNERS_0_STATISTICS_STARTS"
    ).value,
    "heating.burner.statistics/hours": get_prop(
        "HEATING_BURNERS_0_STATISTICS_HOURS"
    ).value,
    "heating.compressor/active": get_prop("HEATING_COMPRESSOR_ACTIVE").value,
    "heating.compressor.statistics/starts": get_prop(
        "HEATING_COMPRESSOR_STATISTICS_STARTS"
    ).value,
    "heating.compressor.statistics/hours": get_prop(
        "HEATING_COMPRESSOR_STATISTICS_HOURS"
    ).value,
    "heating.sensors.valve.expansion/value": get_prop(
        "HEATING_SENSORS_VALVE_EXPANSION_VALUE"
    ).value,
    "heating.compressors.0.sensors.power/value": get_prop(
        "HEATING_COMPRESSORS_0_SPEED_CURRENT_VALUE"
    ).value,
    "heating.secondaryCircuit.sensors.temperature.return/value": get_prop(
        "HEATING_SENSORS_TEMPERATURE_RETURN_VALUE"
    ).value,
    "heating.errors.active/entries": get_prop("HEATING_ERRORS_ACTIVE_ENTRIES").value,
    "device.errors.active/entries": get_prop("HEATING_ERRORS_ACTIVE_ENTRIES").value,
    "device.messages.info.active/entries": get_prop(
        "DEVICE_MESSAGES_INFO_ENTRIES"
    ).value,
    "device.messages.warnings.active/entries": get_prop(
        "DEVICE_MESSAGES_WARNINGS_RAW_ENTRIES"
    ).value,
    "device.messages.status.active/entries": get_prop(
        "DEVICE_MESSAGES_STATUS_RAW_ENTRIES"
    ).value,
    "heating.circuits.0.operating.programs.comfortHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_0_OPERATING_PROGRAMS_COMFORT_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.1.operating.programs.comfortHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_1_OPERATING_PROGRAMS_COMFORT_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.2.operating.programs.comfortHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_2_OPERATING_PROGRAMS_COMFORT_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.3.operating.programs.comfortHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_3_OPERATING_PROGRAMS_COMFORT_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.0.operating.programs.normalHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_0_OPERATING_PROGRAMS_NORMAL_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.1.operating.programs.normalHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_1_OPERATING_PROGRAMS_NORMAL_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.2.operating.programs.normalHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_2_OPERATING_PROGRAMS_NORMAL_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.3.operating.programs.normalHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_3_OPERATING_PROGRAMS_NORMAL_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.0.operating.programs.reducedHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_0_OPERATING_PROGRAMS_REDUCED_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.1.operating.programs.reducedHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_1_OPERATING_PROGRAMS_REDUCED_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.2.operating.programs.reducedHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_2_OPERATING_PROGRAMS_REDUCED_TEMPERATUREVALUE"
    ).value,
    "heating.circuits.3.operating.programs.reducedHeating/temperatureValue": get_prop(
        "HEATING_CIRCUITS_3_OPERATING_PROGRAMS_REDUCED_TEMPERATUREVALUE"
    ).value,
    "heating.primaryCircuit.valves.fourThreeWay/active": get_prop(
        "HEATING_PRIMARYCIRCUIT_VALVES_FOURTHREEWAY_ACTIVE"
    ).value,
}

CRITICAL_HP_ERRORS = [
    "A9",
    "F.839",
    "F.864",
    "F.881",
    "F.1006",
    "F.1007",
    "F.1074",
    "F.1076",
    "F.1077",
    "F.1078",
]

CRITICAL_FUEL_CELL_ERRORS = {
    "F.167": {"panasonic": "F1F0", "artemis": "adf_514"},
    "F.168": {"panasonic": "F2F0", "artemis": "adf_515"},
    "F.169": {"panasonic": "F3F0", "artemis": "adf_516"},
    "F.173": {"panasonic": "C9F1", "artemis": "adf_505"},
    "F.189": {"panasonic": "11F0", "artemis": "adf_383"},
    "F.190": {"panasonic": "1EF0", "artemis": "adf_396"},
    "F.191": {"panasonic": "1EF1", "artemis": "adf_397"},
    "F.194": {"panasonic": "02F2", "artemis": "adf_382"},
    "F.195": {"panasonic": "12F0", "artemis": "adf_384"},
    "F.196": {"panasonic": "13F0", "artemis": "adf_385"},
    "F.197": {"panasonic": "14F0", "artemis": "adf_386"},
    "F.198": {"panasonic": "17F0", "artemis": "adf_387"},
    "F.199": {"panasonic": "19F0", "artemis": "adf_388"},
    "F.200": {"panasonic": "1AF0", "artemis": "adf_389"},
    "F.201": {"panasonic": "1AF2", "artemis": "adf_391"},
    "F.202": {"panasonic": "1AF3", "artemis": "adf_392"},
    "F.203": {"panasonic": "1AF1", "artemis": "adf_390"},
    "F.204": {"panasonic": "1AF4", "artemis": "adf_393"},
    "F.205": {"panasonic": "1DF0", "artemis": "adf_395"},
    "F.206": {"panasonic": "1FF0", "artemis": "adf_398"},
    "F.207": {"panasonic": "23F0", "artemis": "adf_399"},
    "F.208": {"panasonic": "23F1", "artemis": "adf_400"},
    "F.209": {"panasonic": "23F2", "artemis": "adf_401"},
    "F.210": {"panasonic": "24F0", "artemis": "adf_402"},
    "F.211": {"panasonic": "25F0", "artemis": "adf_403"},
    "F.212": {"panasonic": "31F1", "artemis": "adf_404"},
    "F.213": {"panasonic": "31F3", "artemis": "adf_405"},
    "F.214": {"panasonic": "31F4", "artemis": "adf_406"},
    "F.215": {"panasonic": "31F5", "artemis": "adf_407"},
    "F.217": {"panasonic": "34F0", "artemis": "adf_408"},
    "F.218": {"panasonic": "34F1", "artemis": "adf_409"},
    "F.219": {"panasonic": "34F2", "artemis": "adf_410"},
    "F.220": {"panasonic": "34F3", "artemis": "adf_411"},
    "F.221": {"panasonic": "34F4", "artemis": "adf_412"},
    "F.222": {"panasonic": "34F6", "artemis": "adf_413"},
    "F.223": {"panasonic": "37F0", "artemis": "adf_414"},
    "F.224": {"panasonic": "37F1", "artemis": "adf_415"},
    "F.225": {"panasonic": "37F2", "artemis": "adf_416"},
    "F.226": {"panasonic": "37F3", "artemis": "adf_417"},
    "F.227": {"panasonic": "37F4", "artemis": "adf_418"},
    "F.228": {"panasonic": "3BF0", "artemis": "adf_419"},
    "F.229": {"panasonic": "3BF1", "artemis": "adf_420"},
    "F.230": {"panasonic": "3BF2", "artemis": "adf_421"},
    "F.231": {"panasonic": "3BF3", "artemis": "adf_422"},
    "F.232": {"panasonic": "3CF0", "artemis": "adf_423"},
    "F.233": {"panasonic": "41F0", "artemis": "adf_424"},
    "F.234": {"panasonic": "41F1", "artemis": "adf_425"},
    "F.235": {"panasonic": "43F0", "artemis": "adf_427"},
    "F.236": {"panasonic": "43F1", "artemis": "adf_428"},
    "F.237": {"panasonic": "44F0", "artemis": "adf_429"},
    "F.238": {"panasonic": "44F1", "artemis": "adf_430"},
    "F.239": {"panasonic": "51F0", "artemis": "adf_431"},
    "F.240": {"panasonic": "51F5", "artemis": "adf_432"},
    "F.241": {"panasonic": "51F6", "artemis": "adf_433"},
    "F.242": {"panasonic": "52F0", "artemis": "adf_434"},
    "F.243": {"panasonic": "54F0", "artemis": "adf_435"},
    "F.244": {"panasonic": "55F0", "artemis": "adf_436"},
    "F.245": {"panasonic": "57F0", "artemis": "adf_437"},
    "F.246": {"panasonic": "58F0", "artemis": "adf_438"},
    "F.247": {"panasonic": "58F2", "artemis": "adf_439"},
    "F.248": {"panasonic": "67F1", "artemis": "adf_440"},
    "F.249": {"panasonic": "67F9", "artemis": "adf_441"},
    "F.250": {"panasonic": "69F3", "artemis": "adf_442"},
    "F.251": {"panasonic": "6BF0", "artemis": "adf_443"},
    "F.252": {"panasonic": "6BF1", "artemis": "adf_444"},
    "F.253": {"panasonic": "6DF0", "artemis": "adf_445"},
    "F.260": {"panasonic": "71F0", "artemis": "adf_446"},
    "F.261": {"panasonic": "72F0", "artemis": "adf_447"},
    "F.262": {"panasonic": "73F0", "artemis": "adf_448"},
    "F.263": {"panasonic": "73F1", "artemis": "adf_449"},
    "F.264": {"panasonic": "73F4", "artemis": "adf_450"},
    "F.265": {"panasonic": "75F3", "artemis": "adf_451"},
    "F.266": {"panasonic": "75F4", "artemis": "adf_452"},
    "F.267": {"panasonic": "75F5", "artemis": "adf_453"},
    "F.268": {"panasonic": "75F6", "artemis": "adf_454"},
    "F.269": {"panasonic": "76F0", "artemis": "adf_455"},
    "F.270": {"panasonic": "7AF0", "artemis": "adf_456"},
    "F.271": {"panasonic": "7AF1", "artemis": "adf_457"},
    "F.272": {"panasonic": "7AF2", "artemis": "adf_458"},
    "F.273": {"panasonic": "7BF0", "artemis": "adf_459"},
    "F.274": {"panasonic": "80F0", "artemis": "adf_460"},
    "F.275": {"panasonic": "80F1", "artemis": "adf_461"},
    "F.276": {"panasonic": "81F0", "artemis": "adf_462"},
    "F.277": {"panasonic": "81F1", "artemis": "adf_463"},
    "F.278": {"panasonic": "82F0", "artemis": "adf_464"},
    "F.279": {"panasonic": "82F1", "artemis": "adf_465"},
    "F.280": {"panasonic": "83F1", "artemis": "adf_466"},
    "F.281": {"panasonic": "86F0", "artemis": "adf_467"},
    "F.282": {"panasonic": "86F1", "artemis": "adf_468"},
    "F.283": {"panasonic": "88F0", "artemis": "adf_469"},
    "F.284": {"panasonic": "88F1", "artemis": "adf_470"},
    "F.285": {"panasonic": "88F2", "artemis": "adf_471"},
    "F.286": {"panasonic": "8AF0", "artemis": "adf_472"},
    "F.287": {"panasonic": "8AF1", "artemis": "adf_473"},
    "F.288": {"panasonic": "91F0", "artemis": "adf_474"},
    "F.289": {"panasonic": "91F1", "artemis": "adf_475"},
    "F.290": {"panasonic": "96F0", "artemis": "adf_476"},
    "F.291": {"panasonic": "96F2", "artemis": "adf_477"},
    "F.292": {"panasonic": "96F3", "artemis": "adf_478"},
    "F.293": {"panasonic": "9AF2", "artemis": "adf_479"},
    "F.294": {"panasonic": "9BF0", "artemis": "adf_481"},
    "F.295": {"panasonic": "A1F0", "artemis": "adf_480"},
    "F.296": {"panasonic": "A8F0", "artemis": "adf_482"},
    "F.297": {"panasonic": "A9F0", "artemis": "adf_483"},
    "F.298": {"panasonic": "B5F1", "artemis": "adf_484"},
    "F.299": {"panasonic": "B6F0", "artemis": "adf_485"},
    "F.300": {"panasonic": "C0F0", "artemis": "adf_486"},
    "F.301": {"panasonic": "C0F1", "artemis": "adf_487"},
    "F.302": {"panasonic": "C0F2", "artemis": "adf_488"},
    "F.303": {"panasonic": "C2F0", "artemis": "adf_489"},
    "F.304": {"panasonic": "C2F1", "artemis": "adf_490"},
    "F.305": {"panasonic": "C2F2", "artemis": "adf_491"},
    "F.306": {"panasonic": "C3F0", "artemis": "adf_492"},
    "F.307": {"panasonic": "C4F0", "artemis": "adf_493"},
    "F.308": {"panasonic": "C4F1", "artemis": "adf_494"},
    "F.309": {"panasonic": "C4F2", "artemis": "adf_495"},
    "F.310": {"panasonic": "C4F3", "artemis": "adf_496"},
    "F.311": {"panasonic": "C5F0", "artemis": "adf_497"},
    "F.312": {"panasonic": "C6F0", "artemis": "adf_498"},
    "F.313": {"panasonic": "C6F2", "artemis": "adf_499"},
    "F.314": {"panasonic": "C6F3", "artemis": "adf_500"},
    "F.315": {"panasonic": "C7F0", "artemis": "adf_501"},
    "F.316": {"panasonic": "C8F0", "artemis": "adf_502"},
    "F.317": {"panasonic": "C8F1", "artemis": "adf_503"},
    "F.318": {"panasonic": "C9F0", "artemis": "adf_504"},
    "F.319": {"panasonic": "DAF0", "artemis": "adf_506"},
    "F.320": {"panasonic": "E1F0", "artemis": "adf_507"},
    "F.321": {"panasonic": "E1F2", "artemis": "adf_508"},
    "F.322": {"panasonic": "E1F4", "artemis": "adf_509"},
    "F.323": {"panasonic": "F0F0", "artemis": "adf_510"},
    "F.324": {"panasonic": "F0F1", "artemis": "adf_511"},
    "F.325": {"panasonic": "F0F2", "artemis": "adf_512"},
    "F.326": {"panasonic": "F0F3", "artemis": "adf_513"},
    "F.327": {"panasonic": "F4F0", "artemis": "adf_517"},
    "F.328": {"panasonic": "F5F0", "artemis": "adf_518"},
    "F.329": {"panasonic": "F6F0", "artemis": "adf_519"},
    "F.475": {"panasonic": "42F1", "artemis": "adf_426"},
    "F.525": {"panasonic": "1BF0", "artemis": "adf_394"},
}

for error_code, data in CRITICAL_FUEL_CELL_ERRORS.items():
    data["feature_name"] = (
        "fuel_cell_error_" + error_code.replace(".", "") + "_" + data["panasonic"]
    ).upper()
    data["feature_id"] = data["artemis"]


LEGACY_IOT_DF_PROPERTIES = [
    "device.timeseries.ignitionTimeSteps/countOne",
    "device.timeseries.ignitionTimeSteps/countTwo",
    "device.timeseries.ignitionTimeSteps/countThree",
    "device.timeseries.ignitionTimeSteps/countFour",
    "device.timeseries.ignitionTimeSteps/countFive",
    "device.timeseries.ignitionTimeSteps/countSix",
    "device.timeseries.ignitionTimeSteps/countSeven",
    "device.timeseries.ignitionTimeSteps/countEight",
    "device.timeseries.ignitionTimeSteps/countNine",
    "device.timeseries.ignitionTimeSteps/countTen",
    "device.errors.active/entries",
    "device.messages.errors.active/entries",
    "device.messages.errors.raw/entries",
    "device.messages.info.active/entries",
    "device.messages.info.raw/entries",
    "device.messages.warnings.active/entries",
    "device.messages.warnings.raw/entries",
    "device.messages.status.active/entries",
    "device.messages.status.raw/entries",
    "ess.inverter.ac.power/activePower",
    "ess.inverter.ac.power/reactivePower",
    "ess.power/value",
    "ess.sensors.temperature.ambient/value",
    "gateway.wifi/strength",
    "heating.boiler.sensors.temperature.commonSupply/value",
    "heating.boiler.sensors.temperature.main/value",
    "heating.boiler.temperature/value",
    "heating.buffer.sensors.temperature.main/value",
    "heating.buffer.sensors.temperature.top/value",
    "heating.burner/active",
    "heating.burner.current.power/value",
    "heating.burner.modulation/value",
    "heating.burner.statistics/starts",
    "heating.burner.statistics/hours",
    "heating.burners.0/active",
    "heating.burners.0.modulation/value",
    "heating.burners.0.statistics/starts",
    "heating.burners.0.statistics/hours",
    "heating.burners.1/active",
    "heating.burners.1.modulation/value",
    "heating.burners.1.statistics/starts",
    "heating.burners.1.statistics/hours",
    "heating.circuits/enabled",
    "heating.circuits.0.heating.curve/shiftValue",
    "heating.circuits.0.heating.curve/slopeValue",
    "heating.circuits.0.heating.schedule/active",
    "heating.circuits.0.heating.schedule/entries",
    "heating.circuits.0/active",
    "heating.circuits.0/name",
    "heating.circuits.0.operating.modes.active/value",
    "heating.circuits.0.operating.programs.comfort/temperatureValue",
    "heating.circuits.0.operating.programs.normal/temperatureValue",
    "heating.circuits.0.operating.programs.reduced/temperatureValue",
    "heating.circuits.0.operating.programs.holiday/active",
    "heating.circuits.0.operating.programs.holidayAtHome/active",
    "heating.circuits.0.operating.programs.screedDrying/active",
    "heating.circuits.0.temperature/value",
    "heating.circuits.0.circulation.pump/status",
    "heating.circuits.0.sensors.temperature.supply/value",
    "heating.circuits.1.heating.curve/shiftValue",
    "heating.circuits.1.heating.curve/slopeValue",
    "heating.circuits.1.heating.schedule/active",
    "heating.circuits.1.heating.schedule/entries",
    "heating.circuits.1/active",
    "heating.circuits.1/name",
    "heating.circuits.1.operating.modes.active/value",
    "heating.circuits.1.operating.programs.comfort/temperatureValue",
    "heating.circuits.1.operating.programs.normal/temperatureValue",
    "heating.circuits.1.operating.programs.reduced/temperatureValue",
    "heating.circuits.1.operating.programs.holiday/active",
    "heating.circuits.1.operating.programs.holidayAtHome/active",
    "heating.circuits.1.operating.programs.screedDrying/active",
    "heating.circuits.1.temperature/value",
    "heating.circuits.1.circulation.pump/status",
    "heating.circuits.1.sensors.temperature.supply/value",
    "heating.circuits.2.heating.curve/shiftValue",
    "heating.circuits.2.heating.curve/slopeValue",
    "heating.circuits.2.heating.schedule/active",
    "heating.circuits.2.heating.schedule/entries",
    "heating.circuits.2/active",
    "heating.circuits.2/name",
    "heating.circuits.2.operating.modes.active/value",
    "heating.circuits.2.operating.programs.comfort/temperatureValue",
    "heating.circuits.2.operating.programs.normal/temperatureValue",
    "heating.circuits.2.operating.programs.reduced/temperatureValue",
    "heating.circuits.2.operating.programs.holiday/active",
    "heating.circuits.2.operating.programs.holidayAtHome/active",
    "heating.circuits.2.operating.programs.screedDrying/active",
    "heating.circuits.2.temperature/value",
    "heating.circuits.2.circulation.pump/status",
    "heating.circuits.2.sensors.temperature.supply/value",
    "heating.circuits.3.heating.curve/shiftValue",
    "heating.circuits.3.heating.curve/slopeValue",
    "heating.circuits.3.heating.schedule/active",
    "heating.circuits.3.heating.schedule/entries",
    "heating.circuits.3/active",
    "heating.circuits.3/name",
    "heating.circuits.3.operating.modes.active/value",
    "heating.circuits.3.operating.programs.comfort/temperatureValue",
    "heating.circuits.3.operating.programs.normal/temperatureValue",
    "heating.circuits.3.operating.programs.reduced/temperatureValue",
    "heating.circuits.3.operating.programs.holiday/active",
    "heating.circuits.3.operating.programs.holidayAtHome/active",
    "heating.circuits.3.operating.programs.screedDrying/active",
    "heating.circuits.3.temperature/value",
    "heating.circuits.3.circulation.pump/status",
    "heating.circuits.3.sensors.temperature.supply/value",
    "heating.compressor/active",
    "heating.compressor.statistics/starts",
    "heating.compressor.statistics/hours",
    "heating.compressors.0/active",
    "heating.compressors.0.heat.production.dhw.week/value",
    "heating.compressors.0.heat.production.heating.week/value",
    "heating.compressors.0.heater.crankcase/active",
    "heating.compressors.0.power.consumption.dhw.week/value",
    "heating.compressors.0.power.consumption.heating.week/value",
    "heating.compressors.0.statistics/starts",
    "heating.compressors.0.statistics/hours",
    "heating.compressors.0/phase",
    "heating.compressors.0.sensors.temperature.inlet/value",
    "heating.compressors.0.sensors.temperature.outlet/value",
    "heating.compressors.0.sensors.pressure.inlet/value",
    "heating.compressors.0.sensors.pressure.outlet/value",
    "heating.compressors.0.sensors.power/value",
    "heating.compressors.0.speed.current/value",
    "heating.configuration.secondaryHeatGenerator.modeOnError/mode",
    "heating.device.emergencyOperation/active",
    "heating.device.mainECU/runtime",
    "heating.device.time.offset/value",
    "heating.dhw.charging/active",
    "heating.dhw.pumps.circulation/status",
    "heating.dhw.pumps.primary/status",
    "heating.dhw.sensors.temperature.hotWaterStorage/value",
    "heating.dhw.sensors.temperature.hotWaterStorage.bottom/value",
    "heating.dhw.sensors.temperature.hotWaterStorage.top/value",
    "heating.dhw.sensors.temperature.outlet/value",
    "heating.economizers.0.sensors.temperature.liquid/value",
    "heating.evaporators.0.heater.base/active",
    "heating.evaporators.0.sensors.temperature.liquid/value",
    "heating.errors.active/entries",
    "heating.flue.sensors.temperature.main/value",
    "heating.fuelCell.operating.phase/value",
    "heating.fuelCell.sensors.temperature.return/value",
    "heating.fuelCell.sensors.temperature.supply/value",
    "heating.fuelCell.statistics/productionHours",
    "heating.fuelCell.statistics/productionStarts",
    "heating.gas.consumption.dhw/day",
    "heating.gas.consumption.fuelCell/day",
    "heating.gas.consumption.heating/day",
    "heating.gas.consumption.total/day",
    "heating.heatingRod.status/overall",
    "heating.heatingRod.status/level1",
    "heating.heatingRod.status/level2",
    "heating.heatingRod.status/level3",
    "heating.noise.reduction.operating.programs.active/value",
    "heating.power.consumption.dhw/day",
    "heating.power.consumption.heating/day",
    "heating.power.consumption.total/day",
    "heating.power.consumption.cooling/day",
    "heating.power.cumulativeProduced/value",
    "heating.power.cumulativePurchased/value",
    "heating.power.cumulativeSold/value",
    "heating.power.production.cumulative/value",
    "heating.power.production.current/value",
    "heating.power.purchase.cumulative/value",
    "heating.power.sold.cumulative/value",
    "heating.primaryCircuit.fans.0.current/value",
    "heating.primaryCircuit.fans.1.current/value",
    "heating.primaryCircuit.sensors.rotation/value",
    "heating.primaryCircuit.sensors.temperature.return/value",
    "heating.primaryCircuit.sensors.temperature.supply/value",
    "heating.primaryCircuit.valves.fourThreeWay/active",
    "heating.primaryCircuit.valves.fourWay/state",
    "heating.secondaryCircuit.operation.state/currentValue",
    "heating.secondaryCircuit.operation.state/targetValue",
    "heating.secondaryCircuit.sensors.temperature.return/value",
    "heating.secondaryCircuit.sensors.temperature.supply/value",
    "heating.secondaryCircuit.temperature.return.minimum/value",
    "heating.secondaryCircuit.valves.fourThreeWay/current",
    "heating.secondaryCircuit.valves.fourThreeWay/target",
    "heating.sensors.power.output/value",
    "heating.sensors.pressure.hotGas/value",
    "heating.sensors.pressure.suctionGas/value",
    "heating.sensors.pressure.supply/value",
    "heating.sensors.temperature.allengra/value",
    "heating.sensors.temperature.hotGas/value",
    "heating.sensors.temperature.hydraulicSeparator/value",
    "heating.sensors.temperature.liquidGas/value",
    "heating.sensors.temperature.outside/value",
    "heating.sensors.temperature.return/value",
    "heating.sensors.temperature.suctionGas/value",
    "heating.sensors.valve.expansion/value",
    "heating.sensors.valve.0.expansion/value",
    "heating.sensors.valve.1.expansion/value",
    "heating.sensors.volumetricFlow.allengra/value",
    "heating.sensors.volumetricFlow.return/value",
    "heating.solar/active",
    "heating.solar.pumps.circuit/status",
    "heating.solar.sensors.temperature.dhw/value",
    "heating.solar.sensors.temperature.collector/value",
    "heating.valves.diverter.fuelCellDhw/position",
    "heating.valves.diverter.heatDhw/position",
    "pcc.phaseOne.power/activePower",
    "pcc.phaseThree.power/activePower",
    "pcc.phaseThree.power/reactivePower",
    "pcc.phaseTwo.power/activePower",
    "pcc.transfer.power.exchange/value",
    "photovoltaic.string.voltage/stringTwo",
    "photovoltaic.string.voltage/stringOne",
    "ventilation.fan.supply/current",
    "ventilation.fan.exhaust/current",
    "ventilation.sensors.temperature.outside/value",
    "ventilation.sensors.temperature.exhaust/value",
    "ventilation.sensors.temperature.supply/value",
]

LEGACY_IOT_INTERPOLATED_DF_PROPERTIES = [
    "heating.boiler.sensors.temperature.commonSupply/value",
    "heating.boiler.sensors.temperature.main/value",
    "heating.secondaryCircuit.sensors.temperature.supply/value",
    "heating.dhw.sensors.temperature.hotWaterStorage/value",
    "heating.dhw.sensors.temperature.outlet/value",
]

LEGACY_IOT_PIVOT_DF_PROPERTIES = [
    "device.timeseries.ignitionTimeSteps/countOne",
    "device.timeseries.ignitionTimeSteps/countTwo",
    "device.timeseries.ignitionTimeSteps/countThree",
    "device.timeseries.ignitionTimeSteps/countFour",
    "device.timeseries.ignitionTimeSteps/countFive",
    "device.timeseries.ignitionTimeSteps/countSix",
    "device.timeseries.ignitionTimeSteps/countSeven",
    "device.timeseries.ignitionTimeSteps/countEight",
    "device.timeseries.ignitionTimeSteps/countNine",
    "ess.sensors.temperature.ambient/value",
    "device.timeseries.ignitionTimeSteps/countTen",
    "device.errors.active/entries",
    "device.messages.errors.active/entries",
    "device.messages.errors.raw/entries",
    "device.messages.info.active/entries",
    "device.messages.info.raw/entries",
    "device.messages.warnings.active/entries",
    "device.messages.warnings.raw/entries",
    "device.messages.status.active/entries",
    "device.messages.status.raw/entries",
    "gateway.wifi/strength",
    "heating.boiler.sensors.temperature.commonSupply/value",
    "heating.boiler.sensors.temperature.main/value",
    "heating.burner.modulation/value",
    "heating.burner.statistics/starts",
    "heating.burner.statistics/hours",
    "heating.burners.0.modulation/value",
    "heating.burners.0.statistics/starts",
    "heating.burners.0.statistics/hours",
    "heating.buffer.sensors.temperature.main/value",
    "heating.buffer.sensors.temperature.top/value",
    "heating.circuits.0.operating.programs.screedDrying/active",
    "heating.circuits.0.temperature/value",
    "heating.circuits.1.operating.programs.screedDrying/active",
    "heating.circuits.1.temperature/value",
    "heating.circuits.2.operating.programs.screedDrying/active",
    "heating.circuits.2.temperature/value",
    "heating.circuits.3.operating.programs.screedDrying/active",
    "heating.circuits.3.temperature/value",
    "heating.compressor/active",
    "heating.compressor.statistics/starts",
    "heating.compressor.statistics/hours",
    "heating.compressors.0/active",
    "heating.compressors.0.heat.production.dhw.week/value",
    "heating.compressors.0.heat.production.heating.week/value",
    "heating.compressors.0.heater.crankcase/active",
    "heating.compressors.0.power.consumption.dhw.week/value",
    "heating.compressors.0.power.consumption.heating.week/value",
    "heating.compressors.0.statistics/starts",
    "heating.compressors.0.statistics/hours",
    "heating.compressors.0/phase",
    "heating.compressors.0.sensors.temperature.inlet/value",
    "heating.compressors.0.sensors.temperature.outlet/value",
    "heating.compressors.0.sensors.pressure.inlet/value",
    "heating.compressors.0.sensors.pressure.outlet/value",
    "heating.compressors.0.sensors.power/value",
    "heating.compressors.0.speed.current/value",
    "heating.configuration.secondaryHeatGenerator.modeOnError/mode",
    "heating.device.emergencyOperation/active",
    "heating.device.time.offset/value",
    "heating.dhw.charging/active",
    "heating.dhw.pumps.circulation/status",
    "heating.dhw.pumps.primary/status",
    "heating.dhw.sensors.temperature.hotWaterStorage/value",
    "heating.dhw.sensors.temperature.hotWaterStorage.bottom/value",
    "heating.dhw.sensors.temperature.hotWaterStorage.top/value",
    "heating.dhw.sensors.temperature.outlet/value",
    "heating.economizers.0.sensors.temperature.liquid/value",
    "heating.evaporators.0.heater.base/active",
    "heating.evaporators.0.sensors.temperature.liquid/value",
    "heating.errors.active/entries",
    "heating.flue.sensors.temperature.main/value",
    "heating.fuelCell.operating.phase/value",
    "heating.fuelCell.sensors.temperature.return/value",
    "heating.fuelCell.sensors.temperature.supply/value",
    "heating.fuelCell.statistics/productionHours",
    "heating.fuelCell.statistics/productionStarts",
    "heating.gas.consumption.dhw/day",
    "heating.gas.consumption.fuelCell/day",
    "heating.gas.consumption.heating/day",
    "heating.gas.consumption.total/day",
    "heating.heatingRod.status/overall",
    "heating.heatingRod.status/level1",
    "heating.heatingRod.status/level2",
    "heating.heatingRod.status/level3",
    "heating.noise.reduction.operating.programs.active/value",
    "heating.power.consumption.dhw/day",
    "heating.power.consumption.heating/day",
    "heating.power.consumption.total/day",
    "heating.power.consumption.cooling/day",
    "heating.power.production.cumulative/value",
    "heating.power.production.current/value",
    "heating.power.purchase.cumulative/value",
    "heating.power.sold.cumulative/value",
    "heating.primaryCircuit.fans.0.current/value",
    "heating.primaryCircuit.fans.1.current/value",
    "heating.primaryCircuit.sensors.rotation/value",
    "heating.primaryCircuit.sensors.temperature.return/value",
    "heating.primaryCircuit.sensors.temperature.supply/value",
    "heating.primaryCircuit.valves.fourThreeWay/active",
    "heating.primaryCircuit.valves.fourWay/state",
    "heating.secondaryCircuit.operation.state/currentValue",
    "heating.secondaryCircuit.operation.state/targetValue",
    "heating.secondaryCircuit.sensors.temperature.return/value",
    "heating.secondaryCircuit.sensors.temperature.supply/value",
    "heating.secondaryCircuit.temperature.return.minimum/value",
    "heating.secondaryCircuit.valves.fourThreeWay/current",
    "heating.secondaryCircuit.valves.fourThreeWay/target",
    "heating.sensors.pressure.hotGas/value",
    "heating.sensors.pressure.suctionGas/value",
    "heating.sensors.pressure.supply/value",
    "heating.sensors.temperature.allengra/value",
    "heating.sensors.temperature.hotGas/value",
    "heating.sensors.temperature.hydraulicSeparator/value",
    "heating.sensors.temperature.liquidGas/value",
    "heating.sensors.temperature.outside/value",
    "heating.sensors.temperature.return/value",
    "heating.sensors.temperature.suctionGas/value",
    "heating.sensors.valve.expansion/value",
    "heating.sensors.valve.0.expansion/value",
    "heating.sensors.valve.1.expansion/value",
    "heating.sensors.volumetricFlow.allengra/value",
    "heating.sensors.volumetricFlow.return/value",
    "heating.solar.pumps.circuit/status",
    "heating.solar.sensors.temperature.dhw/value",
    "heating.solar.sensors.temperature.collector/value",
    "heating.valves.diverter.fuelCellDhw/position",
    "heating.valves.diverter.heatDhw/position",
    "ventilation.fan.supply/current",
    "ventilation.fan.exhaust/current",
    "ventilation.sensors.temperature.outside/value",
    "ventilation.sensors.temperature.exhaust/value",
    "ventilation.sensors.temperature.supply/value",
]

LEGACY_IOT_CONFIG_DF_PROPERTIES = [
    "device.configuration/circuitsActive",
    "ess.battery.0.information/capacityOfEachModule",
    "ess.battery.1.information/capacityOfEachModule",
    "ess.battery.2.information/capacityOfEachModule",
    "ess.battery.3.information/capacityOfEachModule",
    "ess.battery.4.information/capacityOfEachModule",
    "ess.battery.5.information/capacityOfEachModule",
    "ess.battery.0.information/energyOfModule",
    "ess.battery.1.information/energyOfModule",
    "ess.battery.2.information/energyOfModule",
    "ess.battery.3.information/energyOfModule",
    "ess.battery.4.information/energyOfModule",
    "ess.battery.5.information/energyOfModule",
    "ess.battery.0.information/stateOfHealth",
    "ess.battery.1.information/stateOfHealth",
    "ess.battery.2.information/stateOfHealth",
    "ess.battery.3.information/stateOfHealth",
    "ess.battery.4.information/stateOfHealth",
    "ess.battery.5.information/stateOfHealth",
    "ess.battery.capacityNominal/value",
    "ess.battery/enabled",
    "heating.callForHeat.configuration.regulation/mode",
    "heating.callForHeat.heating.curve.presets/value",
    "heating.callForHeat.heating.curve/shiftValue",
    "heating.callForHeat.heating.curve/slopeValue",
    "heating.callForHeat.temperature/value",
    "heating.callForHeat/active",
    "heating.circuits.0.heating.curve/shiftValue",
    "heating.circuits.0.heating.curve/slopeValue",
    "heating.circuits.0.heating.schedule/active",
    "heating.circuits.0.heating.schedule/entries",
    "heating.circuits.0/active",
    "heating.circuits.0/name",
    "heating.circuits.0.dhw.schedule/active",
    "heating.circuits.0.dhw.schedule/entries",
    "heating.circuits.0.operating.modes.active/value",
    "heating.circuits.0.operating.programs.comfort/temperatureValue",
    "heating.circuits.0.operating.programs.comfortHeating/temperatureValue",
    "heating.circuits.0.operating.programs.normal/temperatureValue",
    "heating.circuits.0.operating.programs.normalHeating/temperatureValue",
    "heating.circuits.0.operating.programs.reduced/temperatureValue",
    "heating.circuits.0.operating.programs.reducedHeating/temperatureValue",
    "heating.circuits.0.operating.programs.holiday/active",
    "heating.circuits.0.operating.programs.holidayAtHome/active",
    "heating.circuits.0.operating.programs.screedDrying/active",
    "heating.circuits.0.temperature.levels/maxValue",
    "heating.circuits.1.dhw.schedule/active",
    "heating.circuits.1.dhw.schedule/entries",
    "heating.circuits.1.heating.curve/shiftValue",
    "heating.circuits.1.heating.curve/slopeValue",
    "heating.circuits.1.heating.schedule/active",
    "heating.circuits.1.heating.schedule/entries",
    "heating.circuits.1/active",
    "heating.circuits.1/name",
    "heating.circuits.1.operating.modes.active/value",
    "heating.circuits.1.operating.programs.comfort/temperatureValue",
    "heating.circuits.1.operating.programs.comfortHeating/temperatureValue",
    "heating.circuits.1.operating.programs.normal/temperatureValue",
    "heating.circuits.1.operating.programs.normalHeating/temperatureValue",
    "heating.circuits.1.operating.programs.reduced/temperatureValue",
    "heating.circuits.1.operating.programs.reducedHeating/temperatureValue",
    "heating.circuits.1.operating.programs.holiday/active",
    "heating.circuits.1.operating.programs.holidayAtHome/active",
    "heating.circuits.1.operating.programs.screedDrying/active",
    "heating.circuits.1.temperature.levels/maxValue",
    "heating.circuits.2.dhw.schedule/active",
    "heating.circuits.2.dhw.schedule/entries",
    "heating.circuits.2.heating.curve/shiftValue",
    "heating.circuits.2.heating.curve/slopeValue",
    "heating.circuits.2.heating.schedule/active",
    "heating.circuits.2.heating.schedule/entries",
    "heating.circuits.2/active",
    "heating.circuits.2/name",
    "heating.circuits.2.operating.modes.active/value",
    "heating.circuits.2.operating.programs.comfort/temperatureValue",
    "heating.circuits.2.operating.programs.comfortHeating/temperatureValue",
    "heating.circuits.2.operating.programs.normal/temperatureValue",
    "heating.circuits.2.operating.programs.normalHeating/temperatureValue",
    "heating.circuits.2.operating.programs.reduced/temperatureValue",
    "heating.circuits.2.operating.programs.reducedHeating/temperatureValue",
    "heating.circuits.2.operating.programs.holiday/active",
    "heating.circuits.2.operating.programs.holidayAtHome/active",
    "heating.circuits.2.operating.programs.screedDrying/active",
    "heating.circuits.2.temperature.levels/maxValue",
    "heating.circuits.3.dhw.schedule/active",
    "heating.circuits.3.dhw.schedule/entries",
    "heating.circuits.3.heating.curve/shiftValue",
    "heating.circuits.3.heating.curve/slopeValue",
    "heating.circuits.3.heating.schedule/active",
    "heating.circuits.3.heating.schedule/entries",
    "heating.circuits.3/active",
    "heating.circuits.3/name",
    "heating.circuits.3.operating.modes.active/value",
    "heating.circuits.3.operating.programs.comfort/temperatureValue",
    "heating.circuits.3.operating.programs.comfortHeating/temperatureValue",
    "heating.circuits.3.operating.programs.normal/temperatureValue",
    "heating.circuits.3.operating.programs.normalHeating/temperatureValue",
    "heating.circuits.3.operating.programs.reduced/temperatureValue",
    "heating.circuits.3.operating.programs.reducedHeating/temperatureValue",
    "heating.circuits.3.operating.programs.holiday/active",
    "heating.circuits.3.operating.programs.holidayAtHome/active",
    "heating.circuits.3.operating.programs.screedDrying/active",
    "heating.circuits.3.temperature.levels/maxValue",
    "heating.configuration.cooling/mode",
    "heating.configuration.gasType/value",
    "heating.configuration.heatingRod.dhw/useApproved",
    "heating.configuration.heatingRod.general/useApproved",
    "heating.configuration.heatingRod.heating/useApproved",
    "heating.configuration.multiFamilyHouse/active",
    "heating.configuration.regulation/mode",
    "heating.device.emergencyOperation/active",
    "heating.device.time.offset/value",
    "heating.dhw/active",
    "heating.dhw.operating.modes.active/value",
    "heating.dhw/status",
    "heating.dhw.schedule/active",
    "heating.dhw.temperature.hysteresis/value",
    "heating.dhw.temperature.main/value",
    "heating.dhw.schedule/entries",
    "heating.fuelCell.operating.modes.active/value",
    "heating.fuelCell.operating.modes.holidayWithFuelCellOff/active",
    "heating.fuelCell.operating.modes.holidayWithFuelCellOn/active",
    "heating.fuelCell.operating.phase/value",
    "heating.operating.programs.holiday/active",
    "heating.operating.programs.holidayAtHome/active",
    "heating.solar/active",
    "heating.spf.dhw/value",
    "heating.spf.heating/value",
    "heating.spf.total/value",
    "ventilation.bypass.position/value",
    "ventilation.levels.levelOne/volumeFlow",
    "ventilation.levels.levelTwo/volumeFlow",
    "ventilation.levels.levelThree/volumeFlow",
    "ventilation.levels.levelFour/volumeFlow",
    "ventilation.operating.modes.active/value",
    "ventilation.schedule/entries",
    "ventilation.schedule/active",
]


VAPOR_PRESSURE = {
    "R290": {
        0.427: -60,
        0.45: -59,
        0.474: -58,
        0.499: -57,
        0.525: -56,
        0.552: -55,
        0.581: -54,
        0.61: -53,
        0.641: -52,
        0.673: -51,
        0.706: -50,
        0.74: -49,
        0.776: -48,
        0.813: -47,
        0.851: -46,
        0.891: -45,
        0.932: -44,
        0.974: -43,
        1.018: -42,
        1.064: -41,
        1.111: -40,
        1.16: -39,
        1.211: -38,
        1.263: -37,
        1.317: -36,
        1.372: -35,
        1.43: -34,
        1.489: -33,
        1.55: -32,
        1.613: -31,
        1.678: -30,
        1.745: -29,
        1.814: -28,
        1.886: -27,
        1.959: -26,
        2.034: -25,
        2.112: -24,
        2.192: -23,
        2.274: -22,
        2.358: -21,
        2.445: -20,
        2.534: -19,
        2.626: -18,
        2.72: -17,
        2.817: -16,
        2.916: -15,
        3.018: -14,
        3.123: -13,
        3.23: -12,
        3.34: -11,
        3.453: -10,
        3.568: -9,
        3.687: -8,
        3.809: -7,
        3.933: -6,
        4.06: -5,
        4.191: -4,
        4.325: -3,
        4.461: -2,
        4.601: -1,
        4.745: 0,
        4.891: 1,
        5.041: 2,
        5.194: 3,
        5.351: 4,
        5.511: 5,
        5.675: 6,
        5.842: 7,
        6.013: 8,
        6.188: 9,
        6.366: 10,
        6.548: 11,
        6.734: 12,
        6.924: 13,
        7.118: 14,
        7.315: 15,
        7.517: 16,
        7.723: 17,
        7.932: 18,
        8.146: 19,
        8.365: 20,
        8.587: 21,
        8.814: 22,
        9.045: 23,
        9.281: 24,
        9.521: 25,
        9.765: 26,
        10.01: 27,
        10.27: 28,
        10.53: 29,
        10.79: 30,
        11.06: 31,
        11.33: 32,
        11.61: 33,
        11.89: 34,
        12.18: 35,
        12.47: 36,
        12.77: 37,
        13.07: 38,
        13.38: 39,
        13.69: 40,
        14.01: 41,
        14.34: 42,
        14.67: 43,
        15.0: 44,
        15.34: 45,
        15.69: 46,
        16.04: 47,
        16.4: 48,
        16.76: 49,
        17.13: 50,
        17.51: 51,
        17.89: 52,
        18.28: 53,
        18.67: 54,
        19.07: 55,
        19.48: 56,
        19.89: 57,
        20.31: 58,
        20.74: 59,
        21.17: 60,
        21.61: 61,
        22.05: 62,
        22.5: 63,
        22.96: 64,
        23.43: 65,
        23.9: 66,
        24.38: 67,
        24.87: 68,
        25.37: 69,
        25.87: 70,
        26.38: 71,
        26.9: 72,
        27.42: 73,
        27.95: 74,
        28.49: 75,
        29.04: 76,
        29.6: 77,
        30.16: 78,
        30.74: 79,
        31.32: 80,
        31.91: 81,
        32.51: 82,
        33.12: 83,
        33.73: 84,
        34.36: 85,
        35.0: 86,
        35.64: 87,
        36.3: 88,
        36.97: 89,
        37.64: 90,
        38.33: 91,
        39.03: 92,
        39.74: 93,
        40.46: 94,
        41.2: 95,
        41.95: 96,
    },
    "R32": {
        0.488: -65,
        0.517: -64,
        0.548: -63,
        0.58: -62,
        0.614: -61,
        0.65: -60,
        0.687: -59,
        0.725: -58,
        0.766: -57,
        0.808: -56,
        0.852: -55,
        0.898: -54,
        0.945: -53,
        0.995: -52,
        1.047: -51,
        1.101: -50,
        1.158: -49,
        1.216: -48,
        1.277: -47,
        1.341: -46,
        1.406: -45,
        1.475: -44,
        1.545: -43,
        1.619: -42,
        1.695: -41,
        1.774: -40,
        1.856: -39,
        1.941: -38,
        2.029: -37,
        2.12: -36,
        2.214: -35,
        2.311: -34,
        2.412: -33,
        2.516: -32,
        2.623: -31,
        2.734: -30,
        2.849: -29,
        2.968: -28,
        3.09: -27,
        3.216: -26,
        3.346: -25,
        3.48: -24,
        3.618: -23,
        3.76: -22,
        3.907: -21,
        4.058: -20,
        4.213: -19,
        4.373: -18,
        4.537: -17,
        4.707: -16,
        4.881: -15,
        5.06: -14,
        5.244: -13,
        5.433: -12,
        5.627: -11,
        5.826: -10,
        6.031: -9,
        6.241: -8,
        6.457: -7,
        6.679: -6,
        6.906: -5,
        7.139: -4,
        7.378: -3,
        7.623: -2,
        7.874: -1,
        8.131: 0,
        8.395: 1,
        8.665: 2,
        8.941: 3,
        9.225: 4,
        9.515: 5,
        9.811: 6,
        10.12: 7,
        10.43: 8,
        10.74: 9,
        11.07: 10,
        11.4: 11,
        11.74: 12,
        12.09: 13,
        12.45: 14,
        12.81: 15,
        13.18: 16,
        13.56: 17,
        13.95: 18,
        14.34: 19,
        14.75: 20,
        15.16: 21,
        15.58: 22,
        16.01: 23,
        16.45: 24,
        16.9: 25,
        17.35: 26,
        17.82: 27,
        18.3: 28,
        18.78: 29,
        19.28: 30,
        19.78: 31,
        20.29: 32,
        20.82: 33,
        21.35: 34,
        21.9: 35,
        22.45: 36,
        23.02: 37,
        23.6: 38,
        24.18: 39,
        24.78: 40,
        25.39: 41,
        26.01: 42,
        26.65: 43,
        27.29: 44,
        27.95: 45,
        28.62: 46,
        29.3: 47,
        29.99: 48,
        30.69: 49,
        31.41: 50,
        32.14: 51,
        32.89: 52,
        33.64: 53,
        34.42: 54,
        35.2: 55,
        36.0: 56,
        36.81: 57,
        37.64: 58,
        38.48: 59,
        39.33: 60,
        40.2: 61,
        41.09: 62,
        41.99: 63,
        42.91: 64,
        43.84: 65,
        44.79: 66,
        45.76: 67,
        46.75: 68,
        47.75: 69,
        48.77: 70,
        49.81: 71,
        50.87: 72,
        51.95: 73,
        53.05: 74,
        54.17: 75,
        55.32: 76,
        56.49: 77,
        57.7: 78,
    },
}

BATTERY_STATE_OF_CHARGE_HISTOGRAMS = {
    "0__0_10": {
        "feature_id": "adf_773",
        "feature_name": "state_of_charge_hist_battery_0_bin_0_to_10",
        "battery": 0,
        "left_limit": 0,
        "right_limit": 10,
    },
    "0__10_20": {
        "feature_id": "adf_774",
        "feature_name": "state_of_charge_hist_battery_0_bin_10_to_20",
        "battery": 0,
        "left_limit": 10,
        "right_limit": 20,
    },
    "0__20_30": {
        "feature_id": "adf_775",
        "feature_name": "state_of_charge_hist_battery_0_bin_20_to_30",
        "battery": 0,
        "left_limit": 20,
        "right_limit": 30,
    },
    "0__30_40": {
        "feature_id": "adf_776",
        "feature_name": "state_of_charge_hist_battery_0_bin_30_to_40",
        "battery": 0,
        "left_limit": 30,
        "right_limit": 40,
    },
    "0__40_50": {
        "feature_id": "adf_777",
        "feature_name": "state_of_charge_hist_battery_0_bin_40_to_50",
        "battery": 0,
        "left_limit": 40,
        "right_limit": 50,
    },
    "0__50_60": {
        "feature_id": "adf_778",
        "feature_name": "state_of_charge_hist_battery_0_bin_50_to_60",
        "battery": 0,
        "left_limit": 50,
        "right_limit": 60,
    },
    "0__60_70": {
        "feature_id": "adf_779",
        "feature_name": "state_of_charge_hist_battery_0_bin_60_to_70",
        "battery": 0,
        "left_limit": 60,
        "right_limit": 70,
    },
    "0__70_80": {
        "feature_id": "adf_780",
        "feature_name": "state_of_charge_hist_battery_0_bin_70_to_80",
        "battery": 0,
        "left_limit": 70,
        "right_limit": 80,
    },
    "0__80_90": {
        "feature_id": "adf_781",
        "feature_name": "state_of_charge_hist_battery_0_bin_80_to_90",
        "battery": 0,
        "left_limit": 80,
        "right_limit": 90,
    },
    "0__90_100": {
        "feature_id": "adf_782",
        "feature_name": "state_of_charge_hist_battery_0_bin_90_to_100",
        "battery": 0,
        "left_limit": 90,
        "right_limit": 100,
    },
    "1__0_10": {
        "feature_id": "adf_783",
        "feature_name": "state_of_charge_hist_battery_1_bin_0_to_10",
        "battery": 1,
        "left_limit": 0,
        "right_limit": 10,
    },
    "1__10_20": {
        "feature_id": "adf_784",
        "feature_name": "state_of_charge_hist_battery_1_bin_10_to_20",
        "battery": 1,
        "left_limit": 10,
        "right_limit": 20,
    },
    "1__20_30": {
        "feature_id": "adf_785",
        "feature_name": "state_of_charge_hist_battery_1_bin_20_to_30",
        "battery": 1,
        "left_limit": 20,
        "right_limit": 30,
    },
    "1__30_40": {
        "feature_id": "adf_786",
        "feature_name": "state_of_charge_hist_battery_1_bin_30_to_40",
        "battery": 1,
        "left_limit": 30,
        "right_limit": 40,
    },
    "1__40_50": {
        "feature_id": "adf_787",
        "feature_name": "state_of_charge_hist_battery_1_bin_40_to_50",
        "battery": 1,
        "left_limit": 40,
        "right_limit": 50,
    },
    "1__50_60": {
        "feature_id": "adf_788",
        "feature_name": "state_of_charge_hist_battery_1_bin_50_to_60",
        "battery": 1,
        "left_limit": 50,
        "right_limit": 60,
    },
    "1__60_70": {
        "feature_id": "adf_789",
        "feature_name": "state_of_charge_hist_battery_1_bin_60_to_70",
        "battery": 1,
        "left_limit": 60,
        "right_limit": 70,
    },
    "1__70_80": {
        "feature_id": "adf_790",
        "feature_name": "state_of_charge_hist_battery_1_bin_70_to_80",
        "battery": 1,
        "left_limit": 70,
        "right_limit": 80,
    },
    "1__80_90": {
        "feature_id": "adf_791",
        "feature_name": "state_of_charge_hist_battery_1_bin_80_to_90",
        "battery": 1,
        "left_limit": 80,
        "right_limit": 90,
    },
    "1__90_100": {
        "feature_id": "adf_792",
        "feature_name": "state_of_charge_hist_battery_1_bin_90_to_100",
        "battery": 1,
        "left_limit": 90,
        "right_limit": 100,
    },
    "2__0_10": {
        "feature_id": "adf_793",
        "feature_name": "state_of_charge_hist_battery_2_bin_0_to_10",
        "battery": 2,
        "left_limit": 0,
        "right_limit": 10,
    },
    "2__10_20": {
        "feature_id": "adf_794",
        "feature_name": "state_of_charge_hist_battery_2_bin_10_to_20",
        "battery": 2,
        "left_limit": 10,
        "right_limit": 20,
    },
    "2__20_30": {
        "feature_id": "adf_795",
        "feature_name": "state_of_charge_hist_battery_2_bin_20_to_30",
        "battery": 2,
        "left_limit": 20,
        "right_limit": 30,
    },
    "2__30_40": {
        "feature_id": "adf_796",
        "feature_name": "state_of_charge_hist_battery_2_bin_30_to_40",
        "battery": 2,
        "left_limit": 30,
        "right_limit": 40,
    },
    "2__40_50": {
        "feature_id": "adf_797",
        "feature_name": "state_of_charge_hist_battery_2_bin_40_to_50",
        "battery": 2,
        "left_limit": 40,
        "right_limit": 50,
    },
    "2__50_60": {
        "feature_id": "adf_798",
        "feature_name": "state_of_charge_hist_battery_2_bin_50_to_60",
        "battery": 2,
        "left_limit": 50,
        "right_limit": 60,
    },
    "2__60_70": {
        "feature_id": "adf_799",
        "feature_name": "state_of_charge_hist_battery_2_bin_60_to_70",
        "battery": 2,
        "left_limit": 60,
        "right_limit": 70,
    },
    "2__70_80": {
        "feature_id": "adf_800",
        "feature_name": "state_of_charge_hist_battery_2_bin_70_to_80",
        "battery": 2,
        "left_limit": 70,
        "right_limit": 80,
    },
    "2__80_90": {
        "feature_id": "adf_801",
        "feature_name": "state_of_charge_hist_battery_2_bin_80_to_90",
        "battery": 2,
        "left_limit": 80,
        "right_limit": 90,
    },
    "2__90_100": {
        "feature_id": "adf_802",
        "feature_name": "state_of_charge_hist_battery_2_bin_90_to_100",
        "battery": 2,
        "left_limit": 90,
        "right_limit": 100,
    },
    "3__0_10": {
        "feature_id": "adf_803",
        "feature_name": "state_of_charge_hist_battery_3_bin_0_to_10",
        "battery": 3,
        "left_limit": 0,
        "right_limit": 10,
    },
    "3__10_20": {
        "feature_id": "adf_804",
        "feature_name": "state_of_charge_hist_battery_3_bin_10_to_20",
        "battery": 3,
        "left_limit": 10,
        "right_limit": 20,
    },
    "3__20_30": {
        "feature_id": "adf_805",
        "feature_name": "state_of_charge_hist_battery_3_bin_20_to_30",
        "battery": 3,
        "left_limit": 20,
        "right_limit": 30,
    },
    "3__30_40": {
        "feature_id": "adf_806",
        "feature_name": "state_of_charge_hist_battery_3_bin_30_to_40",
        "battery": 3,
        "left_limit": 30,
        "right_limit": 40,
    },
    "3__40_50": {
        "feature_id": "adf_807",
        "feature_name": "state_of_charge_hist_battery_3_bin_40_to_50",
        "battery": 3,
        "left_limit": 40,
        "right_limit": 50,
    },
    "3__50_60": {
        "feature_id": "adf_808",
        "feature_name": "state_of_charge_hist_battery_3_bin_50_to_60",
        "battery": 3,
        "left_limit": 50,
        "right_limit": 60,
    },
    "3__60_70": {
        "feature_id": "adf_809",
        "feature_name": "state_of_charge_hist_battery_3_bin_60_to_70",
        "battery": 3,
        "left_limit": 60,
        "right_limit": 70,
    },
    "3__70_80": {
        "feature_id": "adf_810",
        "feature_name": "state_of_charge_hist_battery_3_bin_70_to_80",
        "battery": 3,
        "left_limit": 70,
        "right_limit": 80,
    },
    "3__80_90": {
        "feature_id": "adf_811",
        "feature_name": "state_of_charge_hist_battery_3_bin_80_to_90",
        "battery": 3,
        "left_limit": 80,
        "right_limit": 90,
    },
    "3__90_100": {
        "feature_id": "adf_812",
        "feature_name": "state_of_charge_hist_battery_3_bin_90_to_100",
        "battery": 3,
        "left_limit": 90,
        "right_limit": 100,
    },
    "4__0_10": {
        "feature_id": "adf_813",
        "feature_name": "state_of_charge_hist_battery_4_bin_0_to_10",
        "battery": 4,
        "left_limit": 0,
        "right_limit": 10,
    },
    "4__10_20": {
        "feature_id": "adf_814",
        "feature_name": "state_of_charge_hist_battery_4_bin_10_to_20",
        "battery": 4,
        "left_limit": 10,
        "right_limit": 20,
    },
    "4__20_30": {
        "feature_id": "adf_815",
        "feature_name": "state_of_charge_hist_battery_4_bin_20_to_30",
        "battery": 4,
        "left_limit": 20,
        "right_limit": 30,
    },
    "4__30_40": {
        "feature_id": "adf_816",
        "feature_name": "state_of_charge_hist_battery_4_bin_30_to_40",
        "battery": 4,
        "left_limit": 30,
        "right_limit": 40,
    },
    "4__40_50": {
        "feature_id": "adf_817",
        "feature_name": "state_of_charge_hist_battery_4_bin_40_to_50",
        "battery": 4,
        "left_limit": 40,
        "right_limit": 50,
    },
    "4__50_60": {
        "feature_id": "adf_818",
        "feature_name": "state_of_charge_hist_battery_4_bin_50_to_60",
        "battery": 4,
        "left_limit": 50,
        "right_limit": 60,
    },
    "4__60_70": {
        "feature_id": "adf_819",
        "feature_name": "state_of_charge_hist_battery_4_bin_60_to_70",
        "battery": 4,
        "left_limit": 60,
        "right_limit": 70,
    },
    "4__70_80": {
        "feature_id": "adf_820",
        "feature_name": "state_of_charge_hist_battery_4_bin_70_to_80",
        "battery": 4,
        "left_limit": 70,
        "right_limit": 80,
    },
    "4__80_90": {
        "feature_id": "adf_821",
        "feature_name": "state_of_charge_hist_battery_4_bin_80_to_90",
        "battery": 4,
        "left_limit": 80,
        "right_limit": 90,
    },
    "4__90_100": {
        "feature_id": "adf_822",
        "feature_name": "state_of_charge_hist_battery_4_bin_90_to_100",
        "battery": 4,
        "left_limit": 90,
        "right_limit": 100,
    },
    "5__0_10": {
        "feature_id": "adf_823",
        "feature_name": "state_of_charge_hist_battery_5_bin_0_to_10",
        "battery": 5,
        "left_limit": 0,
        "right_limit": 10,
    },
    "5__10_20": {
        "feature_id": "adf_824",
        "feature_name": "state_of_charge_hist_battery_5_bin_10_to_20",
        "battery": 5,
        "left_limit": 10,
        "right_limit": 20,
    },
    "5__20_30": {
        "feature_id": "adf_825",
        "feature_name": "state_of_charge_hist_battery_5_bin_20_to_30",
        "battery": 5,
        "left_limit": 20,
        "right_limit": 30,
    },
    "5__30_40": {
        "feature_id": "adf_826",
        "feature_name": "state_of_charge_hist_battery_5_bin_30_to_40",
        "battery": 5,
        "left_limit": 30,
        "right_limit": 40,
    },
    "5__40_50": {
        "feature_id": "adf_827",
        "feature_name": "state_of_charge_hist_battery_5_bin_40_to_50",
        "battery": 5,
        "left_limit": 40,
        "right_limit": 50,
    },
    "5__50_60": {
        "feature_id": "adf_828",
        "feature_name": "state_of_charge_hist_battery_5_bin_50_to_60",
        "battery": 5,
        "left_limit": 50,
        "right_limit": 60,
    },
    "5__60_70": {
        "feature_id": "adf_829",
        "feature_name": "state_of_charge_hist_battery_5_bin_60_to_70",
        "battery": 5,
        "left_limit": 60,
        "right_limit": 70,
    },
    "5__70_80": {
        "feature_id": "adf_830",
        "feature_name": "state_of_charge_hist_battery_5_bin_70_to_80",
        "battery": 5,
        "left_limit": 70,
        "right_limit": 80,
    },
    "5__80_90": {
        "feature_id": "adf_831",
        "feature_name": "state_of_charge_hist_battery_5_bin_80_to_90",
        "battery": 5,
        "left_limit": 80,
        "right_limit": 90,
    },
    "5__90_100": {
        "feature_id": "adf_832",
        "feature_name": "state_of_charge_hist_battery_5_bin_90_to_100",
        "battery": 5,
        "left_limit": 90,
        "right_limit": 100,
    },
    "total__0_10": {
        "feature_id": "adf_833",
        "feature_name": "state_of_charge_hist_storage_total_bin_0_to_10",
        "battery": "total",
        "left_limit": 0,
        "right_limit": 10,
    },
    "total__10_20": {
        "feature_id": "adf_834",
        "feature_name": "state_of_charge_hist_storage_total_bin_10_to_20",
        "battery": "total",
        "left_limit": 10,
        "right_limit": 20,
    },
    "total__20_30": {
        "feature_id": "adf_835",
        "feature_name": "state_of_charge_hist_storage_total_bin_20_to_30",
        "battery": "total",
        "left_limit": 20,
        "right_limit": 30,
    },
    "total__30_40": {
        "feature_id": "adf_836",
        "feature_name": "state_of_charge_hist_storage_total_bin_30_to_40",
        "battery": "total",
        "left_limit": 30,
        "right_limit": 40,
    },
    "total__40_50": {
        "feature_id": "adf_837",
        "feature_name": "state_of_charge_hist_storage_total_bin_40_to_50",
        "battery": "total",
        "left_limit": 40,
        "right_limit": 50,
    },
    "total__50_60": {
        "feature_id": "adf_838",
        "feature_name": "state_of_charge_hist_storage_total_bin_50_to_60",
        "battery": "total",
        "left_limit": 50,
        "right_limit": 60,
    },
    "total__60_70": {
        "feature_id": "adf_839",
        "feature_name": "state_of_charge_hist_storage_total_bin_60_to_70",
        "battery": "total",
        "left_limit": 60,
        "right_limit": 70,
    },
    "total__70_80": {
        "feature_id": "adf_840",
        "feature_name": "state_of_charge_hist_storage_total_bin_70_to_80",
        "battery": "total",
        "left_limit": 70,
        "right_limit": 80,
    },
    "total__80_90": {
        "feature_id": "adf_841",
        "feature_name": "state_of_charge_hist_storage_total_bin_80_to_90",
        "battery": "total",
        "left_limit": 80,
        "right_limit": 90,
    },
    "total__90_100": {
        "feature_id": "adf_842",
        "feature_name": "state_of_charge_hist_storage_total_bin_90_to_100",
        "battery": "total",
        "left_limit": 90,
        "right_limit": 100,
    },
}

MAT_NRS_INFO_COLUMNS = [
    "material_number",
    "material_dsc",
    "category",
    "category_dsc",
    "product_main_group",
    "product_main_group_dsc",
    "product_group",
    "product_group_dsc",
    "product_area",
    "product_area_dsc",
    "product_sector",
    "product_sector_dsc",
    "mounting_type",
    "mounting_type_dsc",
    "product_name",
    "product_name_dsc",
    "product_type",
    "product_type_dsc",
    "gateway_type",
    "gateway_type_dsc",
    "connectable",
    "connectable_dsc",
    "control_generation",
    "control_generation_dsc",
]

RAW_WEATHER_COLUMNS = [
    "zip_code",
    "country",
    "date_time_utc",
    "humidity",
    "wind_speed",
    "wind_gust_speed",
    "visibility",
    "sea_level_pressure",
    "part_of_day",
    "direct_normal_irradiance",
    "solar_elevation_angle",
    "pressure",
    "solar_hour_angle",
    "dew_point",
    "snowfall",
    "ultraviolet_light_index",
    "solar_radiation",
    "wind_direction",
    "global_horizontal_irradiance",
    "diffuse_horizontal_irradiance",
    "apparent_temperature",
    "azimuth",
    "current_temperature",
    "precipitation",
    "cloud_cover",
]

RENAME_WEATHER_TO_DC = {
    "humidity": "weather.service/humidity",
    "wind_speed": "weather.service/wind_speed",
    "wind_gust_speed": "weather.service/wind_gust_speed",
    "visibility": "weather.service/visibility",
    "sea_level_pressure": "weather.service/sea_level_pressure",
    "part_of_day": "weather.service/part_of_day",
    "direct_normal_irradiance": "weather.service/direct_normal_irradiance",
    "solar_elevation_angle": "weather.service/solar_elevation_angle",
    "pressure": "weather.service/pressure",
    "solar_hour_angle": "weather.service/solar_hour_angle",
    "dew_point": "weather.service/dew_point",
    "snowfall": "weather.service/snowfall",
    "ultraviolet_light_index": "weather.service/ultraviolet_light_index",
    "solar_radiation": "weather.service/solar_radiation",
    "wind_direction": "weather.service/wind_direction",
    "global_horizontal_irradiance": "weather.service/global_horizontal_irradiance",
    "diffuse_horizontal_irradiance": "weather.service/diffuse_horizontal_irradiance",
    "apparent_temperature": "weather.service/apparent_temperature",
    "azimuth": "weather.service/azimuth",
    "current_temperature": "weather.service/current_temperature",
    "precipitation": "weather.service/precipitation",
    "cloud_cover": "weather.service/cloud_cover",
}